// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Status
	//	*AgentMessage_Traffic
	//	*AgentMessage_Alive
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetStatus() *StatusReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentMessage) GetTraffic() *TrafficReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Traffic); ok {
			return x.Traffic
		}
	}
	return nil
}

func (x *AgentMessage) GetAlive() *AliveReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Alive); ok {
			return x.Alive
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Status struct {
	Status *StatusReport `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type AgentMessage_Traffic struct {
	Traffic *TrafficReport `protobuf:"bytes,3,opt,name=traffic,proto3,oneof"`
}

type AgentMessage_Alive struct {
	Alive *AliveReport `protobuf:"bytes,4,opt,name=alive,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Status) isAgentMessage_Payload() {}

func (*AgentMessage_Traffic) isAgentMessage_Payload() {}

func (*AgentMessage_Alive) isAgentMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	CoreType      string                 `protobuf:"bytes,4,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"` // "xray" or "singbox"
	CoreVersion   string                 `protobuf:"bytes,5,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *RegisterRequest) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

type StatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage     float64                `protobuf:"fixed64,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	Uptime        int64                  `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Connections   int32                  `protobuf:"varint,5,opt,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StatusReport) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *StatusReport) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *StatusReport) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *StatusReport) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *StatusReport) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

type TrafficReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserTraffic         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Inbounds      []*InboundTraffic      `protobuf:"bytes,2,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	Outbounds     []*OutboundTraffic     `protobuf:"bytes,3,rep,name=outbounds,proto3" json:"outbounds,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *TrafficReport) GetUsers() []*UserTraffic {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *TrafficReport) GetInbounds() []*InboundTraffic {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *TrafficReport) GetOutbounds() []*OutboundTraffic {
	if x != nil {
		return x.Outbounds
	}
	return nil
}

func (x *TrafficReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UserTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Upload        int64                  `protobuf:"varint,2,opt,name=upload,proto3" json:"upload,omitempty"`
	Download      int64                  `protobuf:"varint,3,opt,name=download,proto3" json:"download,omitempty"`
	UploadRate    int64                  `protobuf:"varint,4,opt,name=upload_rate,json=uploadRate,proto3" json:"upload_rate,omitempty"`       // bytes/s
	DownloadRate  int64                  `protobuf:"varint,5,opt,name=download_rate,json=downloadRate,proto3" json:"download_rate,omitempty"` // bytes/s
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTraffic) Reset() {
	*x = UserTraffic{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTraffic) ProtoMessage() {}

func (x *UserTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTraffic.ProtoReflect.Descriptor instead.
func (*UserTraffic) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UserTraffic) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserTraffic) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *UserTraffic) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

func (x *UserTraffic) GetUploadRate() int64 {
	if x != nil {
		return x.UploadRate
	}
	return 0
}

func (x *UserTraffic) GetDownloadRate() int64 {
	if x != nil {
		return x.DownloadRate
	}
	return 0
}

type InboundTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Upload        int64                  `protobuf:"varint,2,opt,name=upload,proto3" json:"upload,omitempty"`
	Download      int64                  `protobuf:"varint,3,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundTraffic) Reset() {
	*x = InboundTraffic{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundTraffic) ProtoMessage() {}

func (x *InboundTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundTraffic.ProtoReflect.Descriptor instead.
func (*InboundTraffic) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *InboundTraffic) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InboundTraffic) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *InboundTraffic) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

type OutboundTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Upload        int64                  `protobuf:"varint,2,opt,name=upload,proto3" json:"upload,omitempty"`
	Download      int64                  `protobuf:"varint,3,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundTraffic) Reset() {
	*x = OutboundTraffic{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundTraffic) ProtoMessage() {}

func (x *OutboundTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundTraffic.ProtoReflect.Descriptor instead.
func (*OutboundTraffic) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *OutboundTraffic) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundTraffic) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *OutboundTraffic) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

type AliveReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveReport) Reset() {
	*x = AliveReport{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveReport) ProtoMessage() {}

func (x *AliveReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveReport.ProtoReflect.Descriptor instead.
func (*AliveReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AliveReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PanelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PanelMessage_RegisterResponse
	//	*PanelMessage_Config
	//	*PanelMessage_Users
	//	*PanelMessage_Kick
	//	*PanelMessage_RateLimit
	//	*PanelMessage_AliveResponse
	Payload       isPanelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelMessage) Reset() {
	*x = PanelMessage{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelMessage) ProtoMessage() {}

func (x *PanelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelMessage.ProtoReflect.Descriptor instead.
func (*PanelMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *PanelMessage) GetPayload() isPanelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PanelMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *PanelMessage) GetConfig() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *PanelMessage) GetUsers() *UsersUpdate {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_Users); ok {
			return x.Users
		}
	}
	return nil
}

func (x *PanelMessage) GetKick() *KickUsers {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_Kick); ok {
			return x.Kick
		}
	}
	return nil
}

func (x *PanelMessage) GetRateLimit() *RateLimitUpdate {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_RateLimit); ok {
			return x.RateLimit
		}
	}
	return nil
}

func (x *PanelMessage) GetAliveResponse() *AliveResponse {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_AliveResponse); ok {
			return x.AliveResponse
		}
	}
	return nil
}

type isPanelMessage_Payload interface {
	isPanelMessage_Payload()
}

type PanelMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,1,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type PanelMessage_Config struct {
	Config *ConfigUpdate `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

type PanelMessage_Users struct {
	Users *UsersUpdate `protobuf:"bytes,3,opt,name=users,proto3,oneof"`
}

type PanelMessage_Kick struct {
	Kick *KickUsers `protobuf:"bytes,4,opt,name=kick,proto3,oneof"`
}

type PanelMessage_RateLimit struct {
	RateLimit *RateLimitUpdate `protobuf:"bytes,5,opt,name=rate_limit,json=rateLimit,proto3,oneof"`
}

type PanelMessage_AliveResponse struct {
	AliveResponse *AliveResponse `protobuf:"bytes,6,opt,name=alive_response,json=aliveResponse,proto3,oneof"`
}

func (*PanelMessage_RegisterResponse) isPanelMessage_Payload() {}

func (*PanelMessage_Config) isPanelMessage_Payload() {}

func (*PanelMessage_Users) isPanelMessage_Payload() {}

func (*PanelMessage_Kick) isPanelMessage_Payload() {}

func (*PanelMessage_RateLimit) isPanelMessage_Payload() {}

func (*PanelMessage_AliveResponse) isPanelMessage_Payload() {}

type RegisterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TrafficInterval int32                  `protobuf:"varint,3,opt,name=traffic_interval,json=trafficInterval,proto3" json:"traffic_interval,omitempty"` // Traffic report interval in seconds
	StatusInterval  int32                  `protobuf:"varint,4,opt,name=status_interval,json=statusInterval,proto3" json:"status_interval,omitempty"`    // Status report interval in seconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetTrafficInterval() int32 {
	if x != nil {
		return x.TrafficInterval
	}
	return 0
}

func (x *RegisterResponse) GetStatusInterval() int32 {
	if x != nil {
		return x.StatusInterval
	}
	return 0
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigUpdate) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *ConfigUpdate) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ConfigUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UsersUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         []*UserConfig          `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	Removed       []string               `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty"` // emails to remove
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersUpdate) Reset() {
	*x = UsersUpdate{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersUpdate) ProtoMessage() {}

func (x *UsersUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersUpdate.ProtoReflect.Descriptor instead.
func (*UsersUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *UsersUpdate) GetAdded() []*UserConfig {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *UsersUpdate) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *UsersUpdate) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type UserConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Flow          string                 `protobuf:"bytes,4,opt,name=flow,proto3" json:"flow,omitempty"`
	AlterId       int32                  `protobuf:"varint,5,opt,name=alter_id,json=alterId,proto3" json:"alter_id,omitempty"`
	Security      string                 `protobuf:"bytes,6,opt,name=security,proto3" json:"security,omitempty"`
	Method        string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	Level         int32                  `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	UploadLimit   int64                  `protobuf:"varint,9,opt,name=upload_limit,json=uploadLimit,proto3" json:"upload_limit,omitempty"`
	DownloadLimit int64                  `protobuf:"varint,10,opt,name=download_limit,json=downloadLimit,proto3" json:"download_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConfig) Reset() {
	*x = UserConfig{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConfig) ProtoMessage() {}

func (x *UserConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConfig.ProtoReflect.Descriptor instead.
func (*UserConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *UserConfig) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserConfig) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserConfig) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *UserConfig) GetAlterId() int32 {
	if x != nil {
		return x.AlterId
	}
	return 0
}

func (x *UserConfig) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *UserConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UserConfig) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserConfig) GetUploadLimit() int64 {
	if x != nil {
		return x.UploadLimit
	}
	return 0
}

func (x *UserConfig) GetDownloadLimit() int64 {
	if x != nil {
		return x.DownloadLimit
	}
	return 0
}

type KickUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUsers) Reset() {
	*x = KickUsers{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUsers) ProtoMessage() {}

func (x *KickUsers) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUsers.ProtoReflect.Descriptor instead.
func (*KickUsers) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *KickUsers) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *KickUsers) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RateLimitUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UploadLimit   int64                  `protobuf:"varint,2,opt,name=upload_limit,json=uploadLimit,proto3" json:"upload_limit,omitempty"`
	DownloadLimit int64                  `protobuf:"varint,3,opt,name=download_limit,json=downloadLimit,proto3" json:"download_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitUpdate) Reset() {
	*x = RateLimitUpdate{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitUpdate) ProtoMessage() {}

func (x *RateLimitUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitUpdate.ProtoReflect.Descriptor instead.
func (*RateLimitUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *RateLimitUpdate) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RateLimitUpdate) GetUploadLimit() int64 {
	if x != nil {
		return x.UploadLimit
	}
	return 0
}

func (x *RateLimitUpdate) GetDownloadLimit() int64 {
	if x != nil {
		return x.DownloadLimit
	}
	return 0
}

type AliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveResponse) Reset() {
	*x = AliveResponse{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveResponse) ProtoMessage() {}

func (x *AliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveResponse.ProtoReflect.Descriptor instead.
func (*AliveResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *AliveResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\xdc\x01\n" +
	"\fAgentMessage\x124\n" +
	"\bregister\x18\x01 \x01(\v2\x16.agent.RegisterRequestH\x00R\bregister\x12-\n" +
	"\x06status\x18\x02 \x01(\v2\x13.agent.StatusReportH\x00R\x06status\x120\n" +
	"\atraffic\x18\x03 \x01(\v2\x14.agent.TrafficReportH\x00R\atraffic\x12*\n" +
	"\x05alive\x18\x04 \x01(\v2\x12.agent.AliveReportH\x00R\x05aliveB\t\n" +
	"\apayload\"\x9a\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tcore_type\x18\x04 \x01(\tR\bcoreType\x12!\n" +
	"\fcore_version\x18\x05 \x01(\tR\vcoreVersion\"\xa7\x01\n" +
	"\fStatusReport\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x01R\tdiskUsage\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x03R\x06uptime\x12 \n" +
	"\vconnections\x18\x05 \x01(\x05R\vconnections\"\xc0\x01\n" +
	"\rTrafficReport\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.agent.UserTrafficR\x05users\x121\n" +
	"\binbounds\x18\x02 \x03(\v2\x15.agent.InboundTrafficR\binbounds\x124\n" +
	"\toutbounds\x18\x03 \x03(\v2\x16.agent.OutboundTrafficR\toutbounds\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x9d\x01\n" +
	"\vUserTraffic\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x16\n" +
	"\x06upload\x18\x02 \x01(\x03R\x06upload\x12\x1a\n" +
	"\bdownload\x18\x03 \x01(\x03R\bdownload\x12\x1f\n" +
	"\vupload_rate\x18\x04 \x01(\x03R\n" +
	"uploadRate\x12#\n" +
	"\rdownload_rate\x18\x05 \x01(\x03R\fdownloadRate\"V\n" +
	"\x0eInboundTraffic\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06upload\x18\x02 \x01(\x03R\x06upload\x12\x1a\n" +
	"\bdownload\x18\x03 \x01(\x03R\bdownload\"W\n" +
	"\x0fOutboundTraffic\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06upload\x18\x02 \x01(\x03R\x06upload\x12\x1a\n" +
	"\bdownload\x18\x03 \x01(\x03R\bdownload\"+\n" +
	"\vAliveReport\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xdc\x02\n" +
	"\fPanelMessage\x12F\n" +
	"\x11register_response\x18\x01 \x01(\v2\x17.agent.RegisterResponseH\x00R\x10registerResponse\x12-\n" +
	"\x06config\x18\x02 \x01(\v2\x13.agent.ConfigUpdateH\x00R\x06config\x12*\n" +
	"\x05users\x18\x03 \x01(\v2\x12.agent.UsersUpdateH\x00R\x05users\x12&\n" +
	"\x04kick\x18\x04 \x01(\v2\x10.agent.KickUsersH\x00R\x04kick\x127\n" +
	"\n" +
	"rate_limit\x18\x05 \x01(\v2\x16.agent.RateLimitUpdateH\x00R\trateLimit\x12=\n" +
	"\x0ealive_response\x18\x06 \x01(\v2\x14.agent.AliveResponseH\x00R\raliveResponseB\t\n" +
	"\apayload\"\x9a\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10traffic_interval\x18\x03 \x01(\x05R\x0ftrafficInterval\x12'\n" +
	"\x0fstatus_interval\x18\x04 \x01(\x05R\x0estatusInterval\"]\n" +
	"\fConfigUpdate\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"d\n" +
	"\vUsersUpdate\x12'\n" +
	"\x05added\x18\x01 \x03(\v2\x11.agent.UserConfigR\x05added\x12\x18\n" +
	"\aremoved\x18\x02 \x03(\tR\aremoved\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\"\x95\x02\n" +
	"\n" +
	"UserConfig\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04flow\x18\x04 \x01(\tR\x04flow\x12\x19\n" +
	"\balter_id\x18\x05 \x01(\x05R\aalterId\x12\x1a\n" +
	"\bsecurity\x18\x06 \x01(\tR\bsecurity\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12\x14\n" +
	"\x05level\x18\b \x01(\x05R\x05level\x12!\n" +
	"\fupload_limit\x18\t \x01(\x03R\vuploadLimit\x12%\n" +
	"\x0edownload_limit\x18\n" +
	" \x01(\x03R\rdownloadLimit\";\n" +
	"\tKickUsers\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"q\n" +
	"\x0fRateLimitUpdate\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12!\n" +
	"\fupload_limit\x18\x02 \x01(\x03R\vuploadLimit\x12%\n" +
	"\x0edownload_limit\x18\x03 \x01(\x03R\rdownloadLimit\"-\n" +
	"\rAliveResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2G\n" +
	"\fAgentService\x127\n" +
	"\aConnect\x12\x13.agent.AgentMessage\x1a\x13.agent.PanelMessage(\x010\x01B\"Z github.com/nextproxy/panel/agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),     // 0: agent.AgentMessage
	(*RegisterRequest)(nil),  // 1: agent.RegisterRequest
	(*StatusReport)(nil),     // 2: agent.StatusReport
	(*TrafficReport)(nil),    // 3: agent.TrafficReport
	(*UserTraffic)(nil),      // 4: agent.UserTraffic
	(*InboundTraffic)(nil),   // 5: agent.InboundTraffic
	(*OutboundTraffic)(nil),  // 6: agent.OutboundTraffic
	(*AliveReport)(nil),      // 7: agent.AliveReport
	(*PanelMessage)(nil),     // 8: agent.PanelMessage
	(*RegisterResponse)(nil), // 9: agent.RegisterResponse
	(*ConfigUpdate)(nil),     // 10: agent.ConfigUpdate
	(*UsersUpdate)(nil),      // 11: agent.UsersUpdate
	(*UserConfig)(nil),       // 12: agent.UserConfig
	(*KickUsers)(nil),        // 13: agent.KickUsers
	(*RateLimitUpdate)(nil),  // 14: agent.RateLimitUpdate
	(*AliveResponse)(nil),    // 15: agent.AliveResponse
}
var file_agent_proto_depIdxs = []int32{
	1,  // 0: agent.AgentMessage.register:type_name -> agent.RegisterRequest
	2,  // 1: agent.AgentMessage.status:type_name -> agent.StatusReport
	3,  // 2: agent.AgentMessage.traffic:type_name -> agent.TrafficReport
	7,  // 3: agent.AgentMessage.alive:type_name -> agent.AliveReport
	4,  // 4: agent.TrafficReport.users:type_name -> agent.UserTraffic
	5,  // 5: agent.TrafficReport.inbounds:type_name -> agent.InboundTraffic
	6,  // 6: agent.TrafficReport.outbounds:type_name -> agent.OutboundTraffic
	9,  // 7: agent.PanelMessage.register_response:type_name -> agent.RegisterResponse
	10, // 8: agent.PanelMessage.config:type_name -> agent.ConfigUpdate
	11, // 9: agent.PanelMessage.users:type_name -> agent.UsersUpdate
	13, // 10: agent.PanelMessage.kick:type_name -> agent.KickUsers
	14, // 11: agent.PanelMessage.rate_limit:type_name -> agent.RateLimitUpdate
	15, // 12: agent.PanelMessage.alive_response:type_name -> agent.AliveResponse
	12, // 13: agent.UsersUpdate.added:type_name -> agent.UserConfig
	0,  // 14: agent.AgentService.Connect:input_type -> agent.AgentMessage
	8,  // 15: agent.AgentService.Connect:output_type -> agent.PanelMessage
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Status)(nil),
		(*AgentMessage_Traffic)(nil),
		(*AgentMessage_Alive)(nil),
	}
	file_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*PanelMessage_RegisterResponse)(nil),
		(*PanelMessage_Config)(nil),
		(*PanelMessage_Users)(nil),
		(*PanelMessage_Kick)(nil),
		(*PanelMessage_RateLimit)(nil),
		(*PanelMessage_AliveResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
